kind: Secret
apiVersion: v1
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backendSecret.jwtSecret | quote }}
  mysql-pass: {{ .Values.backendSecret.mysqlPass | quote }}
  mysql-user: {{ .Values.backendSecret.mysqlUser | quote }}
  mysql-root: {{ .Values.backendSecret.mysqlRoot | quote }}

