kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: satnam45/backend:latest
          imagePullPolicy: Never
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-secret
            - name:  SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/chattingo
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mysql-pass
            - name: SPRING_PROFILES_ACTIVE
              value: development
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: chat-app
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31220
