kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mysql-pass
            - name: MYSQL_DATABASE
              value: chattingo
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mysql-root
            

---

kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: chat-app
spec:
  selector:
    app: database
  ports:
    - port: 3306
      targetPort: 3306
