kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: chat-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/saugat/workdir/data"

