kind: Secret
apiVersion: v1
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
stringData:
  jwt-secret: z9iomEpv/QtMfd2HTXnLzGt/7+R7I38m9k0T4L7GJa0=
  mysql-pass: admin123
  mysql-user: admin
  mysql-root: password
